version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: delivery-system-bd
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: delivery-system
      MYSQL_USER: delivery-system
      MYSQL_PASSWORD: delivery-system
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
